sudo: false
language: go
go:
  - 1.8
  - 1.8.1
before_install:
  - go get -t -v ./...
  - go get github.com/modocache/gover
  - go get github.com/mattn/goveralls
script:
  - go test -coverprofile=gear.coverprofile
  - go test -coverprofile=logging.coverprofile ./logging
  - go test -coverprofile=cors.coverprofile ./middleware/cors
  - go test -coverprofile=favicon.coverprofile ./middleware/favicon
  - go test -coverprofile=static.coverprofile ./middleware/static
  - go test -coverprofile=secure.coverprofile ./middleware/secure
  - gover
  - goveralls -coverprofile=gover.coverprofile -service=travis-ci
