sudo: false
language: go
go:
  - 1.8
  - 1.8.1
  - 1.8.2
  - 1.8.3
  - 1.8.4
  - 1.8.5
  - 1.9
  - 1.9.1
  - 1.9.2
before_install:
  - go get -v ./...
  - go get github.com/stretchr/testify/assert
  - go get gopkg.in/mgo.v2/bson
  - go get golang.org/x/net/http2
  - go get github.com/modocache/gover
  - go get github.com/mattn/goveralls
script:
  - go test -coverprofile=gear.coverprofile
  - go test -coverprofile=logging.coverprofile ./logging
  - go test -coverprofile=cors.coverprofile ./middleware/cors
  - go test -coverprofile=favicon.coverprofile ./middleware/favicon
  - go test -coverprofile=static.coverprofile ./middleware/static
  - go test -coverprofile=secure.coverprofile ./middleware/secure
  - gover
  - goveralls -coverprofile=gover.coverprofile -service=travis-ci
