# Host
port = 3000
# cert_file = "tls/test.crt"
# key_file = "tls/test.key"

# [[upstream]]
# host = "www.test.com"
# servers = ["127.0.0.1:3000", "127.0.0.1:3001"]

# [[upstream]]
# host = "api.test.com"
# servers = ["127.0.0.1:3002", "127.0.0.1:3003", "127.0.0.1:3004"]

[[upstream]]
host = "*"
servers = ["http://www.linuxidc.com/"]
